### ISSUE TITLE
Re:VIEWのバージョン毎にdocker imageに対してtagを切るべき？

### ISSUE THREAD

**Issue by vvakame** [vvakame/docker-review#13]
@kmuto 利用者も増えてきたっぽい(9K pulls!)のでいい加減やるべきかなという気持ちになってきました。

* `./` → `latest` tag 今まで通り最新を追いかける
* `./review-2.3` → Re:VIEW v2.3.x の最新を追いかける。 `docker pull vvakame/review:2.3` 的な
* `./review-2.4` → ry

という感じでいいですかね？(Re:VIEWのバージョニングルールがイマイチわかってないです semverではないはず？

**Comment by vvakame** [comment]
タグ増やすたびにdocker hub上で設定を手動で追加しないとダメぽい(めんど

**Comment by kmuto** [comment]
Re:VIEWのバージョニングはおおむねsemantic verですね。major:後方互換性を派手に壊すかもしれない大々的な更新orたくさんの新機能、minor:できるだけ後方互換性を壊さない機能向上、patch:リリース後発覚した深刻なバグの修正。

また、リリースエンジニアリングについては現状リソースの問題で、masterのみの保守、最新リリースバージョンはそこからのスナップショット扱いでメンテナンスブランチを切ったりはしない（たとえば2.3に何か重大なバグがあったとしてももう知らんがなとなる）です。

**Comment by vvakame** [comment]
なるほど。じゃあ複数ファイルをメンテナンスする必要性は薄くて、gitのtagで運用でも問題なさそうですね…！

**Comment by kmuto** [comment]
はい、tag運用でよいかとー。

**Comment by vvakame** [comment]
よく考えるとRe:VIEWが変わらなくてもDockerfileが変わる可能性があることに気が付きました…。

**Comment by vvakame** [comment]
rootのDockerfileを `./update.sh` 経由でちょっと加工して各ディレクトリに撒くようにしました。
現在docker hubでautomated buildしてる最中なので全部ビルドできたらIssueを閉じます。
