### ISSUE TITLE
`//blankline` がつかえない

### ISSUE THREAD

**Issue by youchan** [vvakame/docker-review#16]
review 2.5.0で使えるようになった(https://github.com/kmuto/review/pull/951 )はずの、 `//bleakline` 以下のようなエラーで使えませんでした。

```
review-pdfmaker: warning: compile error in afterword.tex (ReVIEW::ApplicationError)
review-pdfmaker: warning: afterword.re:17: error: unknown command: //blankline
```

    $ review version
    2.5.0

**Comment by kmuto** [comment]
afterword.reの実際の行はどうなっているでしょう？
以下のようなサンプルは手元では2.5.0 gemで動きました。

```
= おや
はて

//blankline

さて
```

review-compile --target=latex afterword.re でもunknown command/ //blankline になるでしょうか。

**Comment by kmuto** [comment]
ってこれはdockerのほうのissueでしたね。reviewコマンドのほうは2.5.0になっているということなのでたぶん同じだと思うのですが…

**Comment by youchan** [comment]
すいません。Docker imageの中にGemfileをコピーしていたため、実際に使われている(bundlerから実行される)reviewのバージョンが古いのが原因でした。
Gemfileを更新してDocker imageを作りなおしたら正しく処理されました。

おさわがせしました。
