### ISSUE TITLE
LaTeXコンパイルに失敗するケースがある

### ISSUE THREAD

**Issue by kauplan** [vvakame/docker-review#24]
Dockerイメージ「vvakame/review」を使うと、LaTeXコンパイルエラーになることがあるので報告します。
 
### 背景
Re:VIEW初心者向けの「reviewstarter」というサイトを作ってます。
https://kauplan.org/reviewstarter/
これはRe:VIEWの初期設定をGUI画面で行ってからプロジェクトをダウンロードするサイトです。

### 障害と原因
ところがreviewstarterで作ったプロジェクトが、Dockerイメージvvakame/reviewでコンパイルするとエラーになりました。
原因はフォント不足とスタイルファイル不足、そしてTeXLiveのバージョンが微妙に古いせいでした。

### 対処
なので、vvakame/reviewのDockerファイルをフォークして別のDockerイメージを作り、フォントとスタイルファイルの追加とTexLiveのバージョン上げを行いました。
詳細はこちら。
https://github.com/kauplan/docker-review/tree/kauplan/review2.5/review-2.5

プルリクエストを出す予定はないですが、いちおう報告しておこうと思い、Issueを書きました。
読み終わったらクローズしてください。

**Comment by vvakame** [comment]
cc/ @kmuto
