### ISSUE TITLE
Debian 10化

### ISSUE THREAD

**Issue by kmuto** [vvakame/docker-review#39]
debian 10がリリースされたですな。
jlreqとかも使えるので更新していきたい。

この機会にいろいろ整理もします？

**Comment by vvakame** [comment]
ｵｯリリースされたんですね。
整理できる要素を何もわかってないのでお願いします…！
debian 10にあげるのだけはやってみようかな…

**Comment by vvakame** [comment]
#37 で既に試みられてた

**Comment by kmuto** [comment]
#37 更新してみますた。今度はテストのC89のほうに手を入れないと…？

**Comment by kmuto** [comment]
こちらもcloseですね。
