### ISSUE TITLE
poppler-utilsを入れたい

### ISSUE THREAD

**Issue by kmuto** [vvakame/docker-review#43]
imgmath (HTMLやテキストで数式部分をTeX切り出しして画像化する機能)を有効すると、現在はコマンドが不足してエラーになります。

現在のDockerイメージにpoppler-utilsパッケージを入れたいのですが、いかがでしょう。

```
The following additional packages will be installed:
  libnspr4 libnss3 libpoppler82
The following NEW packages will be installed:
  libnspr4 libnss3 libpoppler82 poppler-utils
0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
Need to get 2,963 kB of archives.
After this operation, 8,549 kB of additional disk space will be used.
```

で+8MBです。
あと、これを入れる場合に

- 「# install Re:VIEW environment」に入れる：シンプルで読みやすいがイメージを大規模に作り直しになってしまう
- 末尾に別途入れる

のどっちがよいでしょうか。

**Comment by vvakame** [comment]
ローカルで「意味的にいい感じの場所にｼｭｯと入れちゃいましょう！」という話をした

**Comment by kmuto** [comment]
pdfcropを使うためにはtexlive-extra-utils (60MB)… でかいのぅ
